Repository wirriamm/aunty-ingredients, pull requests merged in 2020-06, with the labels that each got.

#10 Update Listing with cards and images
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/components/_card.scss
  app/assets/stylesheets/components/_index.scss
  app/controllers/listings_controller.rb
  app/controllers/pages_controller.rb
  app/models/listing.rb
  app/views/layouts/application.html.erb
  app/views/listings/index.html.erb
  app/views/listings/new.html.erb
  app/views/pages/home.html.erb
  app/views/shared/_card.html.erb
  app/views/shared/_navbar.html.erb
  db/schema.rb
Labels: front-end

#6 Order payment model
  app/controllers/orders_controller.rb
  app/models/listing.rb
  app/models/order.rb
  app/models/payment.rb
  app/models/user.rb
  app/views/listings/show.html.erb
  app/views/orders/index.html.erb
  config/routes.rb
  db/migrate/20200604122749_create_payments.rb
  db/migrate/20200604122917_create_orders.rb
  db/migrate/20200604145556_add_listing_to_orders.rb
  db/schema.rb
  test/controllers/orders_controller_test.rb
  test/models/order_test.rb
  test/models/payment_test.rb
Labels: setup

#18 Order controller
  .gitignore
  app/controllers/listings_controller.rb
  app/controllers/orders_controller.rb
  app/controllers/pages_controller.rb
  app/views/listings/show.html.erb
  app/views/orders/_order.html.erb
  app/views/orders/index.html.erb
Labels: controller logic

#21 made price show in 2dp for listings#show
  app/views/listings/show.html.erb
Labels: enhancement

#28 Orders controller 2
  app/controllers/orders_controller.rb
  app/controllers/pages_controller.rb
  app/views/listings/show.html.erb
  app/views/orders/index.html.erb
  app/views/pages/home.html.erb
Labels: controller logic

#34 Geocoding initial setup
  Gemfile
  Gemfile.lock
  app/models/user.rb
  config/initializers/geocoder.rb
  db/migrate/20200609085845_add_address_to_users.rb
  db/migrate/20200609090051_add_coordinates_to_users.rb
  db/schema.rb
Labels: SHOULDHAVE, setup

#42 Issue37
  app/controllers/payments_controller.rb
  app/views/listings/show.html.erb
  app/views/orders/index.html.erb
  app/views/payments/index.html.erb
  app/views/payments/show.html.erb
  app/views/shared/_navbar.html.erb
Labels: SHOULDHAVE

#46 [bug patch] Listings#show view edit
  app/views/listings/show.html.erb
Labels: bug

#45 Payment validation
  app/controllers/payments_controller.rb
  app/models/listing.rb
  app/models/payment.rb
  app/models/user.rb
  db/seeds.rb
Labels: MUSTHAVE, controller logic

#58 Added dependent: :destroy to all models in User.rb
  app/models/user.rb
  db/seeds.rb
Labels: bug

#62 Landing page
  app/assets/images/logo.png
  app/assets/images/market.jpg
  app/assets/stylesheets/components/_banner.scss
  app/assets/stylesheets/components/_card.scss
  app/assets/stylesheets/components/_index.scss
  app/assets/stylesheets/config/_bootstrap_variables.scss
  app/views/layouts/application.html.erb
  app/views/listings/index.html.erb
  app/views/pages/home.html.erb
  app/views/shared/_card.html.erb
  app/views/shared/_listing.html.erb
  app/views/shared/_navbar.html.erb
Labels: Active, enhancement, front-end

#60 Allowed soft delete listings and enforced authorization
  app/controllers/listings_controller.rb
  app/controllers/orders_controller.rb
  app/views/listings/show.html.erb
  db/migrate/20200611125300_add_delete_status_to_listings.rb
  db/schema.rb
Labels: MUSTHAVE, controller logic, db

#67 My reservations view
  app/views/listings/index.html.erb
  app/views/payments/index.html.erb
  app/views/payments/show.html.erb
  db/seeds.rb
Labels: front-end

#70 add div for listing show
  app/views/listings/show.html.erb
Labels: front-end

#72 Hide listings near you, listed time, adjusted navbar
  app/views/pages/home.html.erb
  app/views/shared/_listing.html.erb
  app/views/shared/_navbar.html.erb
Labels: front-end

#73 add container to new listing
  app/views/listings/new.html.erb
Labels: front-end

#76 Responsiveness Fix
  app/assets/stylesheets/components/_index.scss
  app/assets/stylesheets/components/_listing.scss
  app/views/layouts/application.html.erb
  app/views/listings/index.html.erb
  app/views/orders/_order.html.erb
  app/views/orders/index.html.erb
  app/views/pages/home.html.erb
  app/views/shared/_listing.html.erb
Labels: COULDHAVE, enhancement, front-end
